### ISSUE TITLE
Not rendering the labels using layout='inline' with django-bootstrap4

### ISSUE THREAD

**Issue by flaviomartins** [dmptrluke/django-csp-helpers#1]
Using a CSPViewMixin on the FormView and CSPFormMixing on the Form itself I am able to get the nonce through to the template.

However, rendering of the form using layout='inline' with bootstrap_form does not render labels inside the input boxes anymore.

**Comment by dmptrluke** [comment]
I changed how I modify widgets in 1a4dd83 (released as 0.6.0), could you give that version a go?

**Comment by flaviomartins** [comment]
Works perfectly now. Thank you for finding a solution so fast!

PS: I am using this now in the forms that have to load ReCaptcha. I override django-recaptcha's js_v3.html template and include the csp_nonce in the script tags.

**Comment by dmptrluke** [comment]
> PS: I am using this now in the forms that have to load ReCaptcha. I override django-recaptcha's js_v3.html template and include the csp_nonce in the script tags.

That's exactly what I use it for in some projects, too.

I'm glad the fix worked!
